"""create session_history and pending_item

Revision ID: 7983b7d50d48
Revises: 
Create Date: 2026-06-08 14:11:14.679331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7983b7d50d48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_item',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('draft', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_history',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('planner', sa.Text(), nullable=False),
    sa.Column('calendar_action', sa.Text(), nullable=False),
    sa.Column('synthesize', sa.Text(), nullable=False),
    sa.Column('calendar_action_open', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_history')
    op.drop_table('pending_item')
    # ### end Alembic commands ###
