"""add session_event table for cross-turn event memory

Revision ID: bf3da8bde9b9
Revises: dc08980b5ded
Create Date: 2026-06-19 12:02:06.582430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf3da8bde9b9'
down_revision: Union[str, Sequence[str], None] = 'dc08980b5ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_unix', sa.Integer(), nullable=False),
    sa.Column('end_unix', sa.Integer(), nullable=False),
    sa.Column('attendees', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_event', schema=None) as batch_op:
        batch_op.create_index('ix_session_event_session_id', ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_event', schema=None) as batch_op:
        batch_op.drop_index('ix_session_event_session_id')

    op.drop_table('session_event')
    # ### end Alembic commands ###
